apiVersion: v1
kind: Service
metadata:
  name: my-maven-repo-service
spec:
  type: NodePort
  selector:
    app: my-maven-repo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
