name: CI/CD Pipeline for Maven Java App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-maven-repo:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-maven-repo:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest' # or specify a version

      - name: Set up Kubeconfig
        run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBECONFIG }}" >> $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-deployment.yaml --validate=false
          kubectl apply -f service.yaml --validate=false
